name: CI
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: release-${{ github.sha }}
jobs:
  flatpak:
    name: Linux Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Flatpak Builder
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6.5
        with:
          bundle: com.grantshipley.Klay.Devel.flatpak
          manifest-path: build-aux/flatpak/com.grantshipley.Klay.Devel.json

      - name: Upload Flatpak Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux Flatpak
          path: com.grantshipley.Klay.Devel.flatpak
