name: Publish Release
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

concurrency:
  group: release-${{ github.sha }}

jobs:
  publish-release:
    name: Build And Publish Release
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Flatpak bundle
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6.5
        with:
          bundle: com.grantshipley.Klay.Devel.flatpak
          manifest-path: build-aux/flatpak/com.grantshipley.Klay.Devel.json

      - name: Create release notes
        run: |
          {
            echo "Klay release"
            echo
            echo "## Download"
            echo "- \`com.grantshipley.Klay.Devel.flatpak\`"
            echo
            echo "## Install"
            echo '```bash'
            echo "flatpak install --user --reinstall ./com.grantshipley.Klay.Devel.flatpak"
            echo "flatpak run com.grantshipley.Klay.Devel"
            echo '```'
          } > release_notes

      - name: Get tag name
        id: get_tag_name
        run: echo tag_name=${GITHUB_REF#refs/tags/} >> $GITHUB_OUTPUT

      - name: Publish release
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: |
            com.grantshipley.Klay.Devel.flatpak
          fail_on_unmatched_files: true
          tag_name: ${{ steps.get_tag_name.outputs.tag_name }}
          body_path: release_notes
